### ISSUE TITLE
How to get pre-trained embedding

### ISSUE THREAD

**Issue by AaronWhite95** [CongBao/AutoencodedMetaEmbedding#1]
May I ask where to find the CBOW embedding that mentioned in your paper:

> CBOW: The Continuous Bag-Of-Words (CBOW) embeddings proposed by Mikolov et al. (2013a). The released version we used contains 929,019 word embeddings (phrase embeddings are discarded) with dimensionality of 300, and is trained on Google News corpus (about 100 billion words).

thanks

**Comment by CongBao** [comment]
@HWZX Please refer to this link https://code.google.com/archive/p/word2vec/
